/* ============================================================
   Catálogo inicial de marcenaria (geometrias leves).
   Dimensões em centímetros. Preços-base em BRL (estimativa).
   ============================================================ */
import type { FurnitureItem, FurnitureConfig, FurnitureCategory } from "./types";

const COMMON_MATS = [
  "mdf-branco",
  "mdf-preto",
  "mdf-claro",
  "mdf-escuro",
  "freijo",
  "carvalho",
  "nogal",
  "cinza-premium",
  "ripado",
  "preto-fosco",
  "branco-acetinado",
];

export const CATEGORY_LABELS: Record<FurnitureCategory, string> = {
  balcao: "Balcões",
  prateleira: "Prateleiras",
  estante: "Estantes",
  gondola: "Gôndolas",
  mesa: "Mesas",
  armario: "Armários",
  painel: "Painéis",
  nicho: "Nichos",
  ilha: "Ilhas",
  bancada: "Bancadas",
  checkout: "Checkout",
  vitrine: "Vitrines",
  closet: "Closets",
  gaveteiro: "Gaveteiros",
  aereo: "Aéreos",
};

export const FURNITURE_CATALOG: FurnitureItem[] = [
  {
    id: "balcao-atendimento",
    name: "Balcão de atendimento",
    category: "balcao",
    defaultWidth: 180, defaultHeight: 105, defaultDepth: 60,
    minWidth: 100, maxWidth: 400, minHeight: 90, maxHeight: 120, minDepth: 45, maxDepth: 90,
    basePrice: 3800, complexity: "medio", materials: [...COMMON_MATS, "vidro-fume"],
    grounded: true, defaults: { led: true, drawers: 2, doors: 2 },
  },
  {
    id: "prateleira-parede",
    name: "Prateleira de parede",
    category: "prateleira",
    defaultWidth: 120, defaultHeight: 4, defaultDepth: 28,
    minWidth: 40, maxWidth: 300, minHeight: 3, maxHeight: 8, minDepth: 18, maxDepth: 45,
    basePrice: 420, complexity: "simples", materials: COMMON_MATS,
    grounded: false, mountHeight: 150, defaults: { suspended: true },
  },
  {
    id: "estante-comercial",
    name: "Estante comercial",
    category: "estante",
    defaultWidth: 200, defaultHeight: 230, defaultDepth: 45,
    minWidth: 80, maxWidth: 400, minHeight: 120, maxHeight: 300, minDepth: 30, maxDepth: 60,
    basePrice: 4200, complexity: "medio", materials: [...COMMON_MATS, "vidro-fume", "metal-preto"],
    grounded: true, defaults: { led: true },
  },
  {
    id: "gondola-central",
    name: "Gôndola central",
    category: "gondola",
    defaultWidth: 180, defaultHeight: 140, defaultDepth: 90,
    minWidth: 100, maxWidth: 360, minHeight: 90, maxHeight: 200, minDepth: 60, maxDepth: 120,
    basePrice: 5200, complexity: "alto", materials: [...COMMON_MATS, "metal-preto"],
    grounded: true, defaults: { led: true },
  },
  {
    id: "mesa-exposicao",
    name: "Mesa de exposição",
    category: "mesa",
    defaultWidth: 110, defaultHeight: 85, defaultDepth: 110,
    minWidth: 60, maxWidth: 220, minHeight: 70, maxHeight: 100, minDepth: 60, maxDepth: 220,
    basePrice: 2200, complexity: "simples", materials: [...COMMON_MATS, "vidro-fume"],
    grounded: true,
  },
  {
    id: "armario-alto",
    name: "Armário alto",
    category: "armario",
    defaultWidth: 90, defaultHeight: 240, defaultDepth: 50,
    minWidth: 40, maxWidth: 200, minHeight: 160, maxHeight: 300, minDepth: 35, maxDepth: 70,
    basePrice: 3400, complexity: "medio", materials: [...COMMON_MATS, "vidro-fume"],
    grounded: true, defaults: { doors: 2 },
  },
  {
    id: "armario-baixo",
    name: "Armário baixo",
    category: "armario",
    defaultWidth: 120, defaultHeight: 85, defaultDepth: 50,
    minWidth: 40, maxWidth: 300, minHeight: 50, maxHeight: 110, minDepth: 35, maxDepth: 70,
    basePrice: 2400, complexity: "simples", materials: [...COMMON_MATS],
    grounded: true, defaults: { doors: 2, drawers: 1 },
  },
  {
    id: "painel-ripado",
    name: "Painel ripado",
    category: "painel",
    defaultWidth: 200, defaultHeight: 260, defaultDepth: 6,
    minWidth: 60, maxWidth: 600, minHeight: 100, maxHeight: 320, minDepth: 3, maxDepth: 12,
    basePrice: 2600, complexity: "medio", materials: ["ripado", "freijo", "carvalho", "nogal", "mdf-escuro"],
    grounded: false, mountHeight: 0, defaults: { led: true, suspended: true },
  },
  {
    id: "painel-tv",
    name: "Painel para TV",
    category: "painel",
    defaultWidth: 220, defaultHeight: 180, defaultDepth: 10,
    minWidth: 100, maxWidth: 500, minHeight: 100, maxHeight: 280, minDepth: 6, maxDepth: 25,
    basePrice: 3000, complexity: "medio", materials: [...COMMON_MATS],
    grounded: false, mountHeight: 0, defaults: { led: true, suspended: true },
  },
  {
    id: "nichos-decorativos",
    name: "Nichos decorativos",
    category: "nicho",
    defaultWidth: 120, defaultHeight: 120, defaultDepth: 25,
    minWidth: 40, maxWidth: 300, minHeight: 40, maxHeight: 300, minDepth: 18, maxDepth: 40,
    basePrice: 1600, complexity: "simples", materials: [...COMMON_MATS],
    grounded: false, mountHeight: 90, defaults: { led: true, suspended: true },
  },
  {
    id: "ilha-central",
    name: "Ilha central",
    category: "ilha",
    defaultWidth: 200, defaultHeight: 95, defaultDepth: 100,
    minWidth: 120, maxWidth: 400, minHeight: 85, maxHeight: 110, minDepth: 70, maxDepth: 160,
    basePrice: 5600, complexity: "alto", materials: [...COMMON_MATS, "metal-preto"],
    grounded: true, defaults: { drawers: 4, doors: 2, led: true },
  },
  {
    id: "bancada-trabalho",
    name: "Bancada de trabalho",
    category: "bancada",
    defaultWidth: 200, defaultHeight: 90, defaultDepth: 60,
    minWidth: 80, maxWidth: 400, minHeight: 80, maxHeight: 105, minDepth: 45, maxDepth: 80,
    basePrice: 2800, complexity: "medio", materials: [...COMMON_MATS, "metal-preto"],
    grounded: true, defaults: { drawers: 2 },
  },
  {
    id: "checkout-caixa",
    name: "Caixa / Checkout",
    category: "checkout",
    defaultWidth: 140, defaultHeight: 105, defaultDepth: 70,
    minWidth: 90, maxWidth: 260, minHeight: 95, maxHeight: 120, minDepth: 50, maxDepth: 100,
    basePrice: 3200, complexity: "medio", materials: [...COMMON_MATS],
    grounded: true, defaults: { led: true, drawers: 1, doors: 1 },
  },
  {
    id: "vitrine-interna",
    name: "Vitrine interna",
    category: "vitrine",
    defaultWidth: 100, defaultHeight: 180, defaultDepth: 50,
    minWidth: 50, maxWidth: 240, minHeight: 100, maxHeight: 240, minDepth: 35, maxDepth: 80,
    basePrice: 4400, complexity: "alto", materials: ["metal-preto", "freijo", "nogal", "preto-fosco"],
    grounded: true, defaults: { led: true, surface: "vidro" },
  },
  {
    id: "guarda-volume",
    name: "Guarda-volume",
    category: "armario",
    defaultWidth: 120, defaultHeight: 180, defaultDepth: 45,
    minWidth: 60, maxWidth: 300, minHeight: 120, maxHeight: 240, minDepth: 35, maxDepth: 60,
    basePrice: 2600, complexity: "medio", materials: [...COMMON_MATS, "metal-preto"],
    grounded: true, defaults: { doors: 4 },
  },
  {
    id: "closet-modular",
    name: "Closet modular",
    category: "closet",
    defaultWidth: 240, defaultHeight: 250, defaultDepth: 60,
    minWidth: 120, maxWidth: 500, minHeight: 180, maxHeight: 300, minDepth: 45, maxDepth: 80,
    basePrice: 6800, complexity: "alto", materials: [...COMMON_MATS, "vidro-fume"],
    grounded: true, defaults: { led: true, drawers: 6, doors: 2 },
  },
  {
    id: "gaveteiro",
    name: "Gaveteiro",
    category: "gaveteiro",
    defaultWidth: 50, defaultHeight: 65, defaultDepth: 50,
    minWidth: 30, maxWidth: 120, minHeight: 30, maxHeight: 110, minDepth: 35, maxDepth: 70,
    basePrice: 1400, complexity: "simples", materials: [...COMMON_MATS],
    grounded: true, defaults: { drawers: 4 },
  },
  {
    id: "bancada-cuba",
    name: "Bancada com cuba",
    category: "bancada",
    defaultWidth: 160, defaultHeight: 90, defaultDepth: 55,
    minWidth: 80, maxWidth: 320, minHeight: 80, maxHeight: 100, minDepth: 45, maxDepth: 70,
    basePrice: 3600, complexity: "alto", materials: [...COMMON_MATS, "metal-preto"],
    grounded: true, defaults: { doors: 2 },
  },
  {
    id: "movel-aereo",
    name: "Móvel aéreo",
    category: "aereo",
    defaultWidth: 120, defaultHeight: 70, defaultDepth: 35,
    minWidth: 40, maxWidth: 300, minHeight: 30, maxHeight: 100, minDepth: 25, maxDepth: 45,
    basePrice: 1900, complexity: "simples", materials: [...COMMON_MATS, "vidro-fume"],
    grounded: false, mountHeight: 150, defaults: { suspended: true, doors: 2, led: true },
  },
  {
    id: "planejado-l",
    name: "Móvel planejado em L",
    category: "armario",
    defaultWidth: 260, defaultHeight: 230, defaultDepth: 60,
    minWidth: 160, maxWidth: 500, minHeight: 120, maxHeight: 300, minDepth: 45, maxDepth: 90,
    basePrice: 7400, complexity: "alto", materials: [...COMMON_MATS, "vidro-fume"],
    grounded: true, defaults: { led: true, drawers: 4, doors: 3 },
  },
];

export const CATALOG_MAP: Record<string, FurnitureItem> = Object.fromEntries(
  FURNITURE_CATALOG.map((i) => [i.id, i])
);

export function defaultConfigFor(item: FurnitureItem): FurnitureConfig {
  return {
    material: item.materials[0],
    finish: "fosco",
    handle: "perfil",
    doors: item.defaults?.doors ?? 0,
    drawers: item.defaults?.drawers ?? 0,
    thickness: 1.8,
    led: item.defaults?.led ?? false,
    suspended: item.defaults?.suspended ?? !item.grounded,
    surface: item.defaults?.surface ?? "madeira",
  };
}
